# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Inceptor"
license = "MIT"
licenselink = "https://github.com/daholino/inceptor/blob/main/LICENSE"
description = "Inceptor is a simple, fast and responsive Hugo theme for blogging."
homepage = "https://github.com/daholino/inceptor"
tags = ["blog"]
features = ["simple", "minimal", "customizable"]
min_version = "0.41.0"

[author]
  name = "Tarik Dahic"
  homepage = "https://tarikdahic.com"
